### ISSUE TITLE
make develop branch the default one

### ISSUE THREAD

**Issue by ael-code** [HPDCS/ROOT-Sim#29]
Since developing is happening on the develop branch it should be the default github branch
In this way all the PR will be automatically issued for this branch [1]

Moreover we can specify in the README that stable code is in the master brach.

[1] https://help.github.com/articles/setting-the-default-branch/

**Comment by alessandropellegrini** [comment]
The `master` branch is the default because we want people to clone by default the stable version.
I prefer the "clone and use" pattern rather than the "clone, read the README, checkout a different branch and then use". I consider Github as a good service for holding and distributing the code, everything related to the development should be done relying on the command line.

Additionally, when a pull request is created, you can specify the target branch for the request. This would create problems to users, with a minor benefit for developers.

Moreover, I'm never merging a pull request directly through github's tool, as this lacks fundamental features like squashing multiple commits.

**Comment by ael-code** [comment]
On 12/07/2016 03:27 PM, Alessandro Pellegrini wrote:
> The |master| branch is the default because we want people to clone by
> default the stable version.
> I prefer the "clone and use" pattern rather than the "clone, read the
> README, checkout a different branch and then use". I consider Github as
> a good service for holding and distributing the code, everything related
> to the development should be done relying on the command line.
> 

I got it.

> Additionally, when a pull request is created, you can specify the target
> branch for the request. This would create problems to users, with a
> minor benefit for developers.
> 
> Moreover, I'm never merging a pull request directly through github's
> tool, as this lacks fundamental features like squashing multiple commits.
> 

Actually I recently noticed that they've added this feature. [1]


[1] https://help.github.com/articles/about-pull-request-merges/

**Comment by alessandropellegrini** [comment]
@ael-code This is interesting, although I think you cannot signoff commits in this way
