### ISSUE TITLE
Ignored Makefiles are still there

### ISSUE THREAD

**Issue by ael-code** [HPDCS/ROOT-Sim#70]
Maybe I'm getting confused...

These three files are present into the git tree:
- `src/arch/linux/modules/cross_state_manager/Makefile`
- `src/arch/linux/modules/intercept/Makefile`
- `src/arch/linux/modules/schedule-hook/Makefile`

But they seems to be excluded in the `.gitignore`:
https://github.com/HPDCS/ROOT-Sim/blob/26b0e842d8d45cdd36ffcea69a344418ea392665/.gitignore#L12

**Comment by alessandropellegrini** [comment]
That's a feature, not a bug! :smile: 

Actually, `.gitignore` is excluding from the repository all `Makefile`s because they are autogenerated from autotools.

There is an important exception to this: Kernel modules `Makefile`s. These are exactly the three which you listed, and which have been force-addess (overriding `.gitignore`) to the repository as they are fundamental to the compiling process.

**Comment by ael-code** [comment]
> These are exactly the three which you listed, and which have been force-addess (overriding .gitignore) to the repository as they are fundamental to the compiling process.

Maybe I didn't get the point. If they are fundamental I suggest to track them otherwise future changes 
to them will be out of the git history

**Comment by alessandropellegrini** [comment]
As said in #71, they have been forced into version control, so they are tracked and `git` sees when you make changes to them.
